name: GitHub Action to Build and Deploy React app to AWS S3
on:
  push:
    branches:
      - main
      - development
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        yarn
        yarn build
